items = [
    "Necklace Set Diamond",
    "BA",
    "BA Diamond",
    "Bangels Button",
    "Button Diamond",
    "C Ear Ring",
    "C Ladies Ring",
    "C Nose Pin C Pendent",
    "CAD",
    "Chain",
    "CPS",
    "Cufflink",
    "Cufflink Diamond",
    "Cufflink Diamond PD",
    "Cufflink Diamond PT",
    "Cufflink PD",
    "Cufflink PT",
    "Ear Ring",
    "Ear Ring Diamond",
    "Gents Diamond Ring",
    "Gents Ring",
    "Guluband Set",
    "Jhumar",
    "Jhumar Karay",
    "Karay",
    "Karay Diamond",
    "Ladies Diamond Ring",
    "Ladies Ring",
    "Mala",
    "Necklace Set",
    "Palladium Diamond",
    "Pazaib",
    "Pendent",
    "Pendent Diamond",
    "Pendent Set",
    "Pendent Set Diamond",
    "Sui Pin",
    "Tie Pin",
    "Tie Pin Diamond"
]
